# SPDX-FileCopyrightText: Copyright (c) 2018-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3.3
  NewCops: enable
  SuggestExtensions: false
Metrics/AbcSize:
  Max: 50
Metrics/MethodLength:
  Max: 50
Metrics/BlockLength:
  Max: 30
Layout/EmptyLineAfterGuardClause:
  Enabled: false
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
